services:
  api:
    build: . # Construye la imagen a partir del Dockerfile en el directorio actual
    container_name: server_fastapi # Nombre del contenedor
    ports: 
      - "5000:5000" # Mapea el puerto 5000 del contenedor al puerto 5000 de la máquina host
    volumes:  # guarda los cambios realizados en el contenedor 
      - ./app:/app/app  # Mapea el directorio actual al directorio /app dentro del contenedor 
